name = "JW3126PkgDev"
uuid = "8b682809-697e-4f52-ba3d-584cce8f38ca"
authors = ["Jan Weidner"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
